[Desktop Entry]
Encoding=UTF-8
Name=Latte Shell
Name[ca]=Intèrpret d'ordres del Latte
Name[ca@valencia]=Intèrpret d'ordes del Latte
Name[de]=Latte-Shell
Name[es]=Consola de Latte
Name[nl]=Latte-shell
Name[pt]=Consola do Latte
Name[sv]=Latte skal
Name[uk]=Оболонка Латте
Name[x-test]=xxLatte Shellxx
Name[zh_TW]=Latte Shell
Comment=Shell provided for the Latte Dock
Comment[ca]=Intèrpret d'ordres proporcionat pel Latte Dock
Comment[ca@valencia]=Intèrpret d'ordes proporcionat pel Latte Dock
Comment[de]=Shell für Latte-Dock
Comment[es]=Shell proporcionada para Latte Dock
Comment[nl]=Shell geleverd voor de Latte Dock
Comment[pt]=Consola oferecida para a área acoplável do Latte
Comment[sv]=Skal tillhandahållet för Latte dockningsfönster
Comment[uk]=Оболонка панелі Латте
Comment[x-test]=xxShell provided for the Latte Dockxx
Comment[zh_TW]=由 Latte Dock 提供的 Shell

Keywords=shell
Keywords[ca]=intèrpret d'ordres
Keywords[ca@valencia]=intèrpret d'ordes
Keywords[de]=Shell
Keywords[es]=consola
Keywords[nl]=shell
Keywords[pt]=consola
Keywords[sk]=shell
Keywords[sv]=skal
Keywords[uk]=оболонка
Keywords[x-test]=xxshellxx
Keywords[zh_TW]=shell
Type=Service

X-KDE-ServiceTypes=Plasma/Shell
X-KDE-ParentApp=latte-dock
X-KDE-PluginInfo-Author=@AUTHOR@
X-KDE-PluginInfo-Email=@EMAIL@
X-KDE-PluginInfo-License=GPLv3+
X-KDE-PluginInfo-Name=org.kde.latte.shell
X-KDE-PluginInfo-Version=@VERSION@
X-KDE-PluginInfo-Website=@WEBSITE@
