[Desktop Entry]
Name[de]=Latte
Name[el]=Latte
Name[es]=Latte
Name[it]=Latte
Name=Latte
Comment[de]=Dock für die Massen
Comment[el]=Πίνακας για όλον τον κόσμο
Comment[es]=Dock para las masas
Comment[it]=Dock per le masse
Comment=Dock for the masses
GenericName[de]=Dock
GenericName[el]=Πίνακας
GenericName[es]=Dock
GenericName[it]=Dock
GenericName=Dock

Version=@VERSION@
Categories=Utility;X-SuSE-DesktopUtility;
Exec=latte-dock %u
Icon=latte-dock
InitialPreference=1
Terminal=false
Type=Application
X-KDE-PluginInfo-Author=@AUTHOR@
X-KDE-PluginInfo-Email=@EMAIL@
X-KDE-PluginInfo-Website=@WEBSITE@
X-KDE-StartupNotify=false
X-DBUS-StartupType=Unique
X-DBUS-ServiceName=org.kde.lattedock
