[Desktop Entry]
Name=Latte
Name[ca]=Latte
Name[ca@valencia]=Latte
Name[de]=Latte
Name[es]=Latte
Name[nl]=Latte
Name[pt]=Latte
Name[sv]=Latte
Name[uk]=Латте
Name[x-test]=xxLattexx
Comment=Dock for the masses
Comment[ca]=Acoblador per a les masses
Comment[ca@valencia]=Acoblador per a les masses
Comment[de]=Dock für die Massen
Comment[es]=Un dock para las masas
Comment[nl]=Dock voor de massa
Comment[pt]=Área acoplável para as massas
Comment[sv]=Dockningsfönster för alla
Comment[uk]=Панель для усіх
Comment[x-test]=xxDock for the massesxx
GenericName=Dock
GenericName[ca]=Acobla
GenericName[ca@valencia]=Acobla
GenericName[de]=Dock
GenericName[es]=Dock
GenericName[nl]=Dock
GenericName[pt]=Área Acoplável
GenericName[sk]=Dok
GenericName[sv]=Dockningsfönster
GenericName[uk]=Панель
GenericName[x-test]=xxDockxx
GenericName[zh_CN]=停靠部件
Icon=latte-dock
Categories=Utility;X-SuSE-DesktopUtility;
Exec=latte-dock %u
InitialPreference=1
StartupNotify=false
Terminal=false
Type=Application
StartupWMClass=latte-dock
X-DBUS-ServiceName=org.kde.lattedock
X-DBUS-StartupType=unique
X-KDE-PluginInfo-Author=@AUTHOR@
X-KDE-PluginInfo-Email=@EMAIL@
X-KDE-PluginInfo-Version=@VERSION@
X-KDE-PluginInfo-Website=@WEBSITE@
X-KDE-StartupNotify=false
X-KDE-SubstituteUID=false

