[Desktop Entry]
Name[de]=Latte
Name[el]=Latte
Name[es]=Latte
Name[it]=Latte
Name[pl]=Latte
Name[pt]=Latte
Name[ru]=Латте
Name[zh_TW]=Latte
Name=Latte
Comment[de]=Dock für die Massen
Comment[el]=Πίνακας για όλον τον κόσμο
Comment[es]=Dock para las masas
Comment[it]=Dock per le masse
Comment[pl]=Dock dla mas
Comment[pt]=Dock para as massas
Comment[ru]=Док в массы
Comment[zh_TW]=給大眾使用的 dock
Comment=Dock for the masses
GenericName[de]=Dock
GenericName[el]=Πίνακας
GenericName[es]=Dock
GenericName[it]=Dock
GenericName[pl]=Dock
GenericName[pt]=Dock
GenericName[ru]=Док
GenericName[zh_TW]=Dock
GenericName=Dock
Icon=latte-dock
Categories=Utility;X-SuSE-DesktopUtility;
Exec=latte-dock.sh %u
InitialPreference=1
StartupNotify=false
Terminal=false
Type=Application
Version=@VERSION@
X-DBUS-ServiceName=org.kde.lattedock
X-DBUS-StartupType=unique
X-KDE-PluginInfo-Author=@AUTHOR@
X-KDE-PluginInfo-Email=@EMAIL@
X-KDE-PluginInfo-Website=@WEBSITE@
X-KDE-StartupNotify=false
X-KDE-SubstituteUID=false

