[Desktop Entry]
Name=Separator
Name[ca]=Separador
Name[ca@valencia]=Separador
Name[cs]=Oddělovač
Name[de]=Abstandshalter
Name[el]=Διαχωριστικό
Name[es]=Separador
Name[fr]=Séparateur
Name[nl]=Scheidingshulpmiddel
Name[pl]=Oddzielacz
Name[pt]=Separador
Name[sk]=Oddeľovač
Name[sv]=Avskiljare
Name[uk]=Роздільник
Name[x-test]=xxSeparatorxx
Name[zh_CN]=分隔符
Name[zh_TW]=分隔符號
Comment=For all your separation tasks
Comment[ca]=Per a totes les tasques de separació
Comment[ca@valencia]=Per a totes les tasques de separació
Comment[de]=Für Latte-Dock und Latte-Plasmoid
Comment[el]=Για όλες τις εργασίες διαχωρισμού σας
Comment[es]=Para todas sus tareas de separación
Comment[nl]=Voor al uw scheidingstaken
Comment[pl]=Dla wszystkich twoich oddzielonych zadań
Comment[pt]=Para todas as suas tarefas de separação
Comment[sv]=För alla dina separationsuppgifter
Comment[uk]=Для відокремлення усіх ваших завдань
Comment[x-test]=xxFor all your separation tasksxx
Comment[zh_TW]=為您所有分開的工作

Encoding=UTF-8
Icon=filename-divider
Keywords=separator
Keywords[ca]=separador
Keywords[ca@valencia]=separador
Keywords[cs]=oddělovač
Keywords[de]=Abstandshalter
Keywords[el]=διαχωριστικό
Keywords[es]=separador
Keywords[nl]=scheiding
Keywords[pl]=oddzielacz
Keywords[pt]=separador
Keywords[sk]=oddeľovač
Keywords[sv]=avskiljare
Keywords[uk]=Роздільник
Keywords[x-test]=xxseparatorxx
Keywords[zh_CN]=分隔符
Keywords[zh_TW]=分隔器
Type=Service

X-Plasma-API=declarativeappletscript
X-Plasma-MainScript=ui/main.qml

X-KDE-PluginInfo-Author=Smith AR
X-KDE-PluginInfo-Category=Utilities
X-KDE-PluginInfo-Email=audoban@openmailbox.org
X-KDE-PluginInfo-License=GPLv3
X-KDE-PluginInfo-Name=audoban.applet.separator
X-KDE-PluginInfo-Version=0.1
X-KDE-PluginInfo-Website=https://github.com/audoban/Separator
X-KDE-ServiceTypes=Plasma/Applet

